import Head from 'next/head'
import { useRef } from 'react'
// import Avater from '../components/avater'
import Footer from '../components/Footer'
import { useRouter } from 'next/router'
import Image1 from '../public/images.png'
import Image from 'next/image'

export default function Home() {
  const router = useRouter()
  const searchInputRef = useRef(null)
  
  const search = (e) => {
    e.preventDefault()
    const term = searchInputRef.current.value
    if(!term) return
    router.push(`/search?term=${term}`)



  }
  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>white Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header component */}
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        {/* left section */}
       <div className='flex space-x-4 items-center'>
        <p className='link'>About</p>
        <p className='link'>Store</p>
       </div>
       {/* right section  */}
       <div className='flex space-x-4 items-center'>
        <p className='link'>Wmail</p>
        <p className='link'>Images</p>

        {/* icon */}

        {/* avater */}
        
        <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" viewBox="0 0 20 20" fill="currentColor">
  <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
        </svg>

        {/* <Avater  url={'https://pbs.twimg.com/profile_images/1570099418413633543/brzRESBX_400x400.jpg'}/> */}
       </div>
      </header>

      {/* body component  */}
     <form className='flex flex-col items-center mt-44 flex-grow w-4/5 '>
      <Image
      src={Image1}
      height={120}
      width={200}
      alt="Google logo"
      />
      <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-width-xl lg:max-w-2xl'>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6" className='h-5 mr-3 text-grey-500'>
  <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
      </svg>
      <input type="text" className='focus:outline-none flex-grow'  ref={searchInputRef}/>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className='h-5 mr-3 text-grey-500'>
  <path stroke-linecap="round" stroke-linejoin="round" d="M12 18.75a6 6 0 006-6v-1.5m-6 7.5a6 6 0 01-6-6v-1.5m6 7.5v3.75m-3.75 0h7.5M12 15.75a3 3 0 01-3-3V4.5a3 3 0 116 0v8.25a3 3 0 01-3 3z" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
  <path stroke-linecap="round" stroke-linejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
</svg>
      </div>
      {/* bton */}
      <div className='manage'>
        <button className='btn' onClick={search}>Google Search</button>
        <button className='btn' onClick={search}>I'm feeling luck</button>
      </div>
     </form>
     {/* footer */}
     <Footer />
    </div>
  )
}
